In [1]:
# NumPy Data Explorer
#This notebook demonstrates NumPy array creation, operations, and analysis.

In [2]:
import numpy as np
import time
print("NumPy Data Explorer Project Started")

NumPy Data Explorer Project Started


In [8]:
# Array Creation 
# 1D array
arr1 = np.array([10, 20, 30, 40, 50])
# 2D array
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])

# Using built-in methods
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 2))
range_arr = np.arange(1, 11)
random_arr = np.random.randint(1, 100, size=10)
print("1D Array:")
print(arr1)
print("\n2D Array:")
print(arr2)


1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Indexing
print("\nIndexing:")
print(arr1[0])
print(arr2[1][2])


Indexing:
10
6


In [ ]:
# Slicing
print("\nSlicing:")
print(arr1[1:4])
print(arr2[:, 1])


Slicing:
[20 30 40]
[2 5]


In [11]:
#Mathematical Oprations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(np.sqrt(a))
print(np.power(a,2))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[3.16227766 4.47213595 5.47722558]
[100 400 900]


In [12]:
#Axis-Wise Operations
matrix = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Row-wise sum:", np.sum(matrix, axis=1))
print("Column-wise sum:", np.sum(matrix,axis=0))

Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]


In [13]:
#Statistical Operations
data = np.array([15, 20, 35, 40, 50])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:",np.max(data))


Mean: 32.0
Median: 35.0
Standard Deviation: 12.884098726725126
Variance: 166.0
Min: 15
Max: 50


In [14]:
#Reshaping Arrays
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#Broadcasting
matrix = np.array([[1, 2, 3],
            [4, 5, 6]])
scalar = 10
result = matrix + scalar
print(result)

[[11 12 13]
 [14 15 16]]


In [17]:
# Save array
np.save("data/sample_array.npy",matrix)
loaded_array = np.load("data/sample_array.npy")
print(loaded_array)

[[1 2 3]
 [4 5 6]]


In [20]:
py_list = list(range(1000000))
start = time.time()
py_list_result = [x * 2 for x in py_list]
print("Python List Time:", time.time()-start)

np_array = np.arange(1000000)
start = time.time()
np_result = np_array * 2
print("NumPy Array Time:", time.time()-start)

Python List Time: 0.08248686790466309
NumPy Array Time: 0.0022864341735839844
